'use strict'


//nav
// const navSlide = ()=>{
//   const burger = document.querySelector('.burger')
//   const nav = document.querySelector('.nav-links')
//   const navLinks= document.querySelectorAll('.nav-links li')

//   burger.addEventListener('click', ()=> {
//       nav.classList.toggle('nav-active')
  
//       navLinks.forEach((link,index) => {
//           if (link.style.animation) {
//               link.style.animation = ''
//           } else{
//           link.style.animation = `navLinkFade 0.5s ease forwards  ${index / 7 + 0}s`
//           }
//       });
//       burger.classList.toggle('toggle')

//   });
// }
// navSlide();
//buttons


function goLinkd() {
  window.open("https://www.linkedin.com/in/cayden-byrne-297107227/")
}
function goGithub() {
    window.open("https://github.com/Cayden-B")
}

function goProject1(){
  window.open("https://cayden-b.github.io/Webpage-rebuild-1/home.html ")
}

















